parameters:
#    erp_game.example.class: ERP\GameBundle\Example

services:
#    erp_game.example:
#        class: %erp_game.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
