parameters:
    database_driver:   pdo_mysql
    database_host:     mysql.leochav.es
    database_port:     ~
    database_name:     erpsimples
    database_user:     erpsimples
    database_password: erpsimples 124124

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
