jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    firewalls:
        login_firewall:
            pattern:    ^/ERP/login$
            anonymous:  ~
        secured_area:
            pattern:    ^/ERP/
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
                default_target_path: game
            logout:
                path:   logout
                target: /ERP/login    
    access_control:
        - { path: ^/ERP/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ERP, roles: ROLE_ADMIN }

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: user123, roles: 'ROLE_USER' }
                    admin: { password: admin123, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        