jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    firewalls:
        login_firewall:
            pattern:    ^/ERP/login$
            anonymous:  ~
        secured_area:
            pattern:    ^/ERP/
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
                default_target_path: game
            logout:
                path:   logout
                target: /ERP/login    
    access_control:
        - { path: ^/ERP/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ERP, roles: ROLE_USER }

    providers:
       administrators:
            entity: { class: ERPGameBundle:Usuario, property: username }

    encoders:
        ERP\GameBundle\Entity\Usuario:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]        