console:
    resource: "@ERPGameBundle/Controller/ConsoleController.php"
    prefix:   /ERP
    type:     annotation

region:
    resource: "@ERPGameBundle/Controller/RegionController.php"
    prefix:   /ERP
    type:     annotation

game:
    resource: "@ERPGameBundle/Controller/GameController.php"
    prefix:   /ERP
    type:     annotation


image:
    resource: "@ERPGameBundle/Controller/ImageController.php"
    prefix:   /ERP
    type:     annotation    
    
    
etiqueta:
    resource: "@ERPGameBundle/Controller/EtiquetaController.php"
    prefix:   /ERP
    type:     annotation  

fornecedor:
    resource: "@ERPGameBundle/Controller/FornecedorController.php"
    prefix:   /ERP
    type:     annotation 
    
cliente:
    resource: "@ERPGameBundle/Controller/ClienteController.php"
    prefix:   /ERP
    type:     annotation     

produtoitem:
    resource: "@ERPGameBundle/Controller/ProdutoItemController.php"
    prefix:   /ERP
    type:     annotation 
    
pedido:
    resource: "@ERPGameBundle/Controller/PedidoController.php"
    prefix:   /ERP
    type:     annotation 
    
secured:
    resource: "@ERPGameBundle/Controller/SecuredController.php"
    prefix:   /ERP
    type:     annotation